# Generated by Django 4.0 on 2021-12-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_students_alter_course_teachers'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
