# Generated by Django 4.0 on 2021-12-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField()),
                ('students', models.ManyToManyField(related_name='students', to='users.User')),
                ('teachers', models.ManyToManyField(related_name='teachers', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='')),
                ('created', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
