# Generated by Django 4.0 on 2021-12-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_students_alter_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
