# Generated by Django 4.0 on 2021-12-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
