# Generated by Django 4.0 on 2022-01-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_lecture_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={},
        ),
        migrations.AlterField(
            model_name='mark',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.homework'),
        ),
    ]
