# Generated by Django 4.0 on 2022-01-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('course', '0016_alter_homework_options_alter_mark_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hometask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('hometask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.hometask')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
